### ISSUE TITLE
CSS pages are loaded insecurely

### ISSUE THREAD

**Issue by benfulton** [hpc-social/good-first-issues#4]
Some of the css files are loaded with http rather than https. Perhaps it's just that "Enforce HTTPS" is not checked in settings? Some browsers will refuse to load the stylesheets, with the error

> Mixed Content: The page at 'https://hpc.social/good-first-issues/' was loaded over HTTPS, but requested an insecure stylesheet 'http://hpc.social/good-first-issues/assets/css/jobs.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by vsoch** [comment]
I just checked the "Enforce https" in settings - does it seem Ok now? Indeed it's just files served from our domain!

**Comment by alansill** [comment]
The W3C markup validator seems unhappy in several ways, but doesnʻt flag any http/https issues:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fhpc.social%2Fgood-first-issues%2F

**Comment by benfulton** [comment]
I looked yesterday and saw no change, but this morning everything looks good! It must have taken a while to get registered.
